In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
datas = pd.read_csv('car performance-dataset.csv')

In [3]:
type(datas)

pandas.core.frame.DataFrame

In [4]:
datas.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [23]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
datas['car name'] = l.fit_transform(datas['car name'])

In [24]:
datas.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   
5  15.0          8         429.0         198    4341          10.0   
6  14.0          8         454.0         220    4354           9.0   
7  14.0          8         440.0         215    4312           8.5   
8  14.0          8         455.0         225    4425          10.0   
9  15.0          8         390.0         190    3850           8.5   

   model year  origin  car name  
0          70       1        49  
1          70       1        36  
2          70       1       231  
3          70       1        14  
4          70       1       161  
5          70       1       141  
6          70       1        54  
7          70       1       223  
8          70       1       241  
9          70       1         1

In [25]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    int64  
dtypes: float64(3), int64(6)
memory usage: 28.1 KB


In [27]:
datas['car name'].unique()

array([ 49,  36, 231,  14, 161, 141,  54, 223, 241,   1, 101, 215,  57,
        30, 274, 220,   8, 150,  95, 282, 211,  16, 258,  22,   7, 133,
        68, 112, 163,  65, 271, 156, 232, 162,  10, 242, 116, 129, 250,
         9,  64, 243, 151, 187, 208, 210, 123, 267,  76, 286, 218, 272,
       105, 293,  63, 158,   2, 192,  31, 203,  75, 183,  11,  48, 143,
       233, 295, 283, 212, 253, 157,  85, 279, 104, 268,  25,  55, 142,
       109, 193,  44, 148, 222,  74,  29,   0, 235,  62, 292, 128, 219,
       207, 263,  87, 174, 188, 121,  59, 244, 124, 209,  17, 294, 113,
       260, 276, 204,  61,  92,  50, 234,  27, 110,  21, 284,  88, 103,
       122, 167, 261, 127, 236, 194,  42, 224,  24,  41, 221,  34,  60,
       154, 266, 240, 287,  12, 296, 171, 125,  40, 254, 108,  51,  66,
       302, 100, 145, 252,  13,  91, 297, 239, 186,  39,  67, 132, 111,
       165,  32, 256, 216,  94, 202, 117, 189,  53,  35, 238, 144, 245,
        58,  70, 160, 288, 251, 269, 155, 107, 262,  89,  23, 18

In [28]:
x = datas.iloc[:,1:8].values
x

array([[  8. , 307. , 130. , ...,  12. ,  70. ,   1. ],
       [  8. , 350. , 165. , ...,  11.5,  70. ,   1. ],
       [  8. , 318. , 150. , ...,  11. ,  70. ,   1. ],
       ...,
       [  4. , 135. ,  84. , ...,  11.6,  82. ,   1. ],
       [  4. , 120. ,  79. , ...,  18.6,  82. ,   1. ],
       [  4. , 119. ,  82. , ...,  19.4,  82. ,   1. ]])

In [29]:
y = datas.iloc[:,0].values

In [30]:
y

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [32]:
x.shape

(398, 7)

In [33]:
x_train

array([[  8. , 318. , 150. , ...,  13.5,  72. ,   1. ],
       [  4. ,  97. ,  60. , ...,  19. ,  71. ,   2. ],
       [  4. ,  97. ,  78. , ...,  15.8,  80. ,   2. ],
       ...,
       [  4. ,  68. ,  49. , ...,  19.5,  73. ,   2. ],
       [  6. , 250. , 100. , ...,  15. ,  71. ,   1. ],
       [  4. ,  90. ,  71. , ...,  16.5,  75. ,   2. ]])

In [34]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
x_train = sd.fit_transform(x_train)
x_test = sd.fit_transform(x_test)

In [35]:
x_train

array([[ 1.49526939,  1.22961301,  1.24359144, ..., -0.79520768,
        -1.13752513, -0.73301171],
       [-0.85285735, -0.92367663, -1.16092059, ...,  1.24411524,
        -1.41177304,  0.5068698 ],
       [-0.85285735, -0.92367663, -0.68001818, ...,  0.05760009,
         1.05645814,  0.5068698 ],
       ...,
       [-0.85285735, -1.206235  , -1.45480539, ...,  1.42950823,
        -0.86327722,  0.5068698 ],
       [ 0.32120602,  0.56706235, -0.09224857, ..., -0.2390287 ,
        -1.41177304, -0.73301171],
       [-0.85285735, -0.99188037, -0.86703579, ...,  0.31715028,
        -0.31478141,  0.5068698 ]])

In [36]:
y_train

array([15. , 27. , 34.3, 26. , 31.6, 33.8, 29. , 18.1, 27.2, 38. , 26. ,
       14. , 22. , 31. , 36.4, 17.6, 17.7, 28. , 20.8, 14. , 20.2, 32.8,
       22.3, 28. , 37. , 27. , 23.2, 13. , 15. , 22. , 24. , 29. , 13. ,
       31.8, 23. , 25.5, 29.9, 13. , 17.5, 46.6, 15.5, 32.9, 14. , 25. ,
       19.4, 15. , 32.4, 31.5, 27. , 19.8, 17. , 33.5, 21. , 23. , 38.1,
       44. , 40.8, 21. , 29. , 17.5, 28. , 26. , 26. , 11. , 37.7, 24.2,
       16. , 16. , 30. , 19. , 27. , 19. , 16. , 16. , 20.3, 21. , 33.5,
       23. , 21.5, 16. , 19. , 37. , 15. , 16. , 26. , 18. , 13. , 21. ,
       29. , 22. , 33. , 22. , 16. , 36. , 20. , 22. , 31.3, 14.5, 29.8,
       13. , 13. , 36. , 20.5, 25. , 27. , 33. , 16.5, 20.6, 30. , 43.4,
       34.7, 11. , 18. , 13. , 16. , 19. , 23. , 25.5, 14. , 24.5, 30. ,
       25.8, 38. , 28.8, 26.6, 17. , 32. , 18.1, 11. , 21. , 36. , 13. ,
       30. , 31. , 14. , 18. , 13. , 21.6, 28. , 23.8, 14. , 27. , 20.2,
       26. , 39.4, 19.9, 19. , 14. , 23.6, 13. , 38

In [60]:
from sklearn.ensemble import RandomForestRegressor
d = RandomForestRegressor (n_estimators=30,random_state = 0)
d.fit(x_train,y_train)


RandomForestRegressor(n_estimators=50, random_state=0)

In [61]:
r = d.predict(x_test)
r

array([14.47 , 23.93 , 14.22 , 20.904, 18.346, 30.39 , 34.754, 20.85 ,
       16.002, 26.502, 37.346, 36.88 , 19.41 , 26.88 , 16.706, 33.296,
       28.272, 27.452, 17.312, 36.572, 16.264, 23.43 , 23.242, 20.442,
       33.398, 26.774, 33.91 , 30.834, 32.034, 16.732, 20.154, 32.852,
       19.398, 34.77 , 21.624, 24.762, 19.578, 16.946, 35.122, 12.52 ,
       13.6  , 15.1  , 28.66 , 33.012, 29.124, 22.878, 20.982, 16.602,
       23.532, 29.95 , 34.93 , 26.53 , 17.388, 27.42 , 15.74 , 12.96 ,
       18.84 , 26.532, 32.002, 15.788, 20.754, 26.06 , 19.88 , 21.496,
       13.5  , 15.1  , 14.12 , 18.974, 24.138, 14.07 , 34.74 , 13.45 ,
       23.228, 18.714, 23.778, 31.704, 28.842, 31.422, 32.038, 14.37 ])

In [62]:
import pickle
pickle.dump(d,open('regression.pkl','wb'))

In [63]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,r)
accuracy

0.897271691430665

In [58]:
r =d.predict(np.array([[8,307,130,3504,12,70,1]]))
r

array([17.62333333])

In [59]:
from sklearn.svm import SVR
svm = SVR(kernel = 'linear')
svm.fit(x_train,y_train)

SVR(kernel='linear')

In [44]:
y_pre = svm.predict(x_test)

In [45]:
from sklearn.metrics import r2_score
accurac = r2_score(y_test,y_pre)

In [46]:
accurac

0.820840225488712